# Generated by Django 3.2.13 on 2023-01-17 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('order', models.ImageField(upload_to='')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('level', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentid', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='StudentID')),
                ('givenname', models.CharField(max_length=50, verbose_name='Given Name')),
                ('middlename', models.CharField(blank=True, max_length=20, verbose_name='Middle Name')),
                ('surname', models.CharField(max_length=20, verbose_name='Surname')),
                ('dateofbirth', models.DateField()),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subjectid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(choices=[('English', 'English'), ('Mathematics', 'Mathematics'), ('Science', 'Science'), ('Social Science', 'Social Science'), ('Arts', 'Arts'), ('Making A Living', 'Making A Living'), ('Health & Physical Education', 'Health & Physical Education')], max_length=50)),
                ('periodscore', models.IntegerField()),
                ('assessmentperiod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saap.assessmentperiod')),
                ('gradelevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saap.gradelevel')),
            ],
        ),
    ]
