# Generated by Django 3.2.13 on 2023-01-17 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saap', '0002_alter_assessmentperiod_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradelevel',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)]),
        ),
    ]
